"""modify player season averages

Revision ID: 12cae71f3617
Revises: 51cb049fb6c8
Create Date: 2026-04-09 14:48:39.097578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cae71f3617'
down_revision: Union[str, None] = '51cb049fb6c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('player_season_averages_team_id_fkey'), 'player_season_averages', type_='foreignkey')
    op.drop_column('player_season_averages', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_season_averages', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('player_season_averages_team_id_fkey'), 'player_season_averages', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
