"""create player season averages table

Revision ID: 1bd6303575da
Revises: 30d5ffecae59
Create Date: 2026-03-16 04:58:26.256054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd6303575da'
down_revision: Union[str, None] = '30d5ffecae59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_averages',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('min_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('points_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fgm_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fga_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ftm_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fta_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tpm_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tpa_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('off_reb_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('def_reb_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tot_reb_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('asts_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stls_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('blks_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tos_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pfs_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fgp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ftp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tpp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('plus_minus_pg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season'], ['seasons.year'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('season', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_season_averages')
    # ### end Alembic commands ###
