"""create player game stats table

Revision ID: 30d5ffecae59
Revises: 5124e8442bf5
Create Date: 2026-03-16 04:38:03.460902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d5ffecae59'
down_revision: Union[str, None] = '5124e8442bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.String(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('tpm', sa.Integer(), nullable=False),
    sa.Column('tpa', sa.Integer(), nullable=False),
    sa.Column('off_reb', sa.Integer(), nullable=False),
    sa.Column('def_reb', sa.Integer(), nullable=False),
    sa.Column('tot_reb', sa.Integer(), nullable=False),
    sa.Column('asts', sa.Integer(), nullable=False),
    sa.Column('stls', sa.Integer(), nullable=False),
    sa.Column('blks', sa.Integer(), nullable=False),
    sa.Column('tos', sa.Integer(), nullable=False),
    sa.Column('pfs', sa.Integer(), nullable=False),
    sa.Column('fgp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ftp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tpp', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_stats')
    # ### end Alembic commands ###
