"""update_team_player_season_averages

Revision ID: 51cb049fb6c8
Revises: bde76166e1b7
Create Date: 2026-04-01 04:48:31.571764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cb049fb6c8'
down_revision: Union[str, None] = 'bde76166e1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'player_season_averages', ['player_id', 'season'])
    op.create_unique_constraint(None, 'team_season_averages', ['team_id', 'season'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_season_averages', type_='unique')
    op.drop_constraint(None, 'player_season_averages', type_='unique')
    # ### end Alembic commands ###
