"""amend_players_with_active

Revision ID: 64101360f15a
Revises: f7bafe3f95ab
Create Date: 2026-03-28 05:27:00.096627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64101360f15a'
down_revision: Union[str, None] = 'f7bafe3f95ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'active')
    # ### end Alembic commands ###
