"""update_team_game_stats

Revision ID: bde76166e1b7
Revises: 37faaa6ce77d
Create Date: 2026-04-01 03:23:17.951407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde76166e1b7'
down_revision: Union[str, None] = '37faaa6ce77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_stats', sa.Column('season', sa.String(), nullable=False))
    op.create_index(op.f('ix_team_game_stats_season'), 'team_game_stats', ['season'], unique=False)
    op.create_foreign_key(None, 'team_game_stats', 'seasons', ['season'], ['season'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_game_stats', type_='foreignkey')
    op.drop_index(op.f('ix_team_game_stats_season'), table_name='team_game_stats')
    op.drop_column('team_game_stats', 'season')
    # ### end Alembic commands ###
