"""replace round with round_label on playoff_game_metadata

Revision ID: 53b5e860b3c9
Revises: f6a1b2c3d4e5
Create Date: 2026-06-03 08:24:55.552921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b5e860b3c9'
down_revision: Union[str, None] = 'f6a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playoff_game_metadata', sa.Column('round_label', sa.String(), nullable=True))
    op.drop_column('playoff_game_metadata', 'round')
    op.create_unique_constraint(None, 'team_playoff_season_averages', ['team_id', 'season'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_playoff_season_averages', type_='unique')
    op.add_column('playoff_game_metadata', sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('playoff_game_metadata', 'round_label')
    # ### end Alembic commands ###
