"""amend_standings

Revision ID: 7ce89d4eb54d
Revises: a99b296966ad
Create Date: 2026-03-27 22:29:10.332062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce89d4eb54d'
down_revision: Union[str, None] = 'a99b296966ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings', sa.Column('points_pg', sa.Numeric(precision=5, scale=1), nullable=False))
    op.add_column('standings', sa.Column('opp_points_pg', sa.Numeric(precision=5, scale=1), nullable=False))
    op.add_column('standings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('standings', 'win_streak')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings', sa.Column('win_streak', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('standings', 'updated_at')
    op.drop_column('standings', 'opp_points_pg')
    op.drop_column('standings', 'points_pg')
    # ### end Alembic commands ###
