"""create standings table

Revision ID: c34ba340ee20
Revises: 1bd6303575da
Create Date: 2026-03-16 05:12:09.104923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34ba340ee20'
down_revision: Union[str, None] = '1bd6303575da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standings',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('conference', sa.String(), nullable=False),
    sa.Column('conference_rank', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('wins_home', sa.Integer(), nullable=False),
    sa.Column('wins_away', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('losses_home', sa.Integer(), nullable=False),
    sa.Column('losses_away', sa.Integer(), nullable=False),
    sa.Column('win_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('games_behind', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('win_L10', sa.Integer(), nullable=False),
    sa.Column('loss_L10', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('win_streak', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['season'], ['seasons.year'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('season', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standings')
    # ### end Alembic commands ###
