"""create_team_season_averages

Revision ID: f7bafe3f95ab
Revises: 61d1dd35b28c
Create Date: 2026-03-27 22:32:12.262477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7bafe3f95ab'
down_revision: Union[str, None] = '61d1dd35b28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_season_averages',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('opponent_points', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('rebounds', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('assists', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('steals', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('blocks', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('turnovers', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('fg_pct', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('three_pct', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('ft_pct', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.year'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'season_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_season_averages')
    # ### end Alembic commands ###
